### PR TITLE
Have data server return retention interval

### PR DESCRIPTION
**Pull request by mjc-gh**
This is useful for when a client needs to manipulate the data such as zero filling the results for graphing.

### CODE REVIEW

**Comment by noahhl** [comment]
Thanks for the pull request!

Looks like some commits unrelated to adding the retention interval snuck into the pull request. I cherry-picked just the  interval patch in https://github.com/noahhl/batsd/commit/97b9146ed980152a3bc3b2dd4a7a63d4dcd388d3, so I'm going to close this request.

**Comment by mjc-gh** [comment]
Ah yes, my pull request was set to master. May open another issue about the jruby json stuff.

**Comment by noahhl** [comment]
Please do with some more details. I haven't needed to include the json gem explicitly either locally or in production, but may be a side effect of version or how jruby was installed.

**Comment by mjc-gh** [comment]
Will do. Can open it later today.

On Mon, Jun 4, 2012 at 11:43 AM, Noah Lorang
reply@reply.github.com
wrote:

> Please do with some more details. I haven't needed to include the json gem explicitly either locally or in production, but may be a side effect of version or how jruby was installed.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noahhl/batsd/pull/6#issuecomment-6102243

## 

http://about.me/mikeycgto

**Pull request closed without merging**
